syntax = "proto3";

package com.exit.common;

option java_multiple_files = true;
option java_package = "com.exit.common.grpc";
option java_outer_classname = "MagazineServiceProto";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service MagazineService {
  rpc GetMagazinesByCategory(GetMagazinesByCategoryRequest) returns (GetMagazinesByCategoryResponse);
  rpc GetMagazine(GetMagazineRequest) returns (GetMagazineResponse);
  rpc ScrapMagazine(ScrapMagazineRequest) returns (ScrapMagazineResponse);
  rpc GetScrapBox(GetScrapBoxRequest) returns (GetScrapBoxResponse);
  rpc GetRecommendedMagazine(GetRecommendedMagazineRequest) returns (GetRecommendedMagazineResponse);
  rpc SearchMagazines(SearchMagazinesRequest) returns (SearchMagazinesResponse);
}

// request
message GetMagazinesByCategoryRequest {
  int64 category_id = 1;
  int32 page_num = 2;
  int64 user_id = 3;
}

message GetMagazineRequest {
  int64 magazine_id = 1;
  int64 user_id = 2;
}

message ScrapMagazineRequest {
  int64 magazine_id = 1;
  int64 user_id = 2;
}

message GetScrapBoxRequest {
  int64 user_id = 1;
  int32 page_num = 2;
}

message GetRecommendedMagazineRequest {
  int64 user_id = 1;
}

message SearchMagazinesRequest {
  string keyword = 1;
  int32 page = 2;
  int32 size = 3;
  int64 user_id = 4;
}

// response
message MagazineItem {
  int64 magazine_id = 1;
  int64 magazine_category_id = 2;
  string magazine_title = 3;
  string magazine_subtitle = 4;
  string magazine_content = 5;
  string magazine_author = 6;
  string author_profile_url = 7;
  string magazine_thumbnail_url = 8;
  google.protobuf.Timestamp created_at = 9;
  bool is_scrap = 10;
}

message GetMagazinesByCategoryResponse {
  repeated MagazineItem magazine_item = 1;
}

message GetMagazineResponse {
    MagazineItem magazine_item = 1;
}

message ScrapMagazineResponse {
  int64 magazine_id = 1;
  bool is_scrapped = 2;
}

message MagazineScrapBoxItem {
  int64 magazine_id = 1;
  string magazine_title = 2;
  string magazine_subtitle = 3;
  string magazine_thumbnail_url = 4;
  google.protobuf.Timestamp created_at = 5;
}

message GetScrapBoxResponse {
  repeated MagazineScrapBoxItem magazine_scrap_box_item = 1;
  bool has_next = 2;
}

message GetRecommendedMagazineResponse {
  repeated MagazineScrapBoxItem recommendMagazine = 1;
}

message SearchMagazinesResponse {
  repeated MagazineItem magazines = 1;
  bool has_next = 3;
}