syntax = "proto3";

package com.exit.common;

option java_multiple_files = true;
option java_package = "com.exit.common.grpc";
option java_outer_classname = "QuestionServiceProto";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service QuestionService {
  rpc QuestionCreate(QuestionCreateRequest) returns (QuestionCreateResponse);
  rpc QuestionReport(QuestionReportRequest) returns (QuestionReportResponse);
  rpc QuestionList(QuestionListRequest) returns (QuestionListResponse);
  rpc CategoryRecommend(CategoryRecommendRequest) returns (CategoryRecommendationResponse);
  rpc SimilarQuestion(SimilarQuestionRequest) returns (SimilarQuestionResponse);
  rpc GetQuestionDetail(QuestionDetailRequest) returns (QuestionDetailResponse);
  rpc GetPopularPost(google.protobuf.Empty) returns (GetPopularPostResponse);
  rpc GetMyQuestion(GetMyQuestionRequest) returns (GetMyQuestionResponse);
  rpc UpdateQuestion(UpdateQuestionRequest) returns (QuestionCreateResponse);
}

message Authority {
  bool can_adopt = 1;
  bool can_delete = 3;
  bool can_modify = 4;
  bool is_third_party = 5;
  bool can_write = 6;
}

message ImageMetadata {
  string filename = 1;
  string content_type = 2;   // e.g. image/jpeg
}

message UploadBytesRequest {
  ImageMetadata meta = 2;
  bytes data = 3;            // 주의: 큰 파일 비권장
}

message ImageObject {
  int64 image_id = 1;
  string image_url = 2;
}

// Request messages
message QuestionCreateRequest {
  string question_title = 1;
  string question_content = 2;
  int64 question_category = 3;
  bool question_urgency = 4;
  string question_answer_type = 5;
  string question_disclosure_type = 6;
  int64 question_writer_id = 7;
  bool question_is_anonymous = 8;
  repeated UploadBytesRequest images = 9;
}

message QuestionReportRequest {
  int64 question_id = 1;
  int64 question_report_writer_id = 2;
  int32 question_report_reason = 3;
  string question_report_content = 4;
}

message QuestionListRequest {
  repeated int64 category_ids = 1;
  string keyword = 2;
  int32 page_num = 3;
  int32 size = 4;
  bool is_answered = 5;
}

message CategoryRecommendRequest {
  string title = 1;
}

message SimilarQuestionRequest {
  string title = 1;
  string content = 2;
}

message QuestionDetailRequest {
  int64 question_id = 1;
  int64 user_id = 2;
}

message GetMyQuestionRequest {
  int64 user_id = 1;
  int32 page_num = 2;
  int32 size = 3;
}

message UpdateQuestionRequest {
  int64 user_id = 1;
  int64 question_id = 2;
  string content = 3;
  repeated int64 deleted_image_id = 4;
  repeated UploadBytesRequest images = 5;
}

// Response messages
message QuestionCreateResponse {
  int64 question_id = 1;
  string question_title = 2;
  string question_content = 3;
  int64 question_category = 4;
  bool question_urgency = 5;
  string question_answer_type = 6;
  string question_disclosure_type = 7;
  int64 question_writer_id = 8;
  string question_writer_name = 9;
  string question_writer_profile = 10;
  repeated ImageObject images = 11;
  google.protobuf.Timestamp created_at = 12;
}

message QuestionReportResponse {
  int64 question_report_id = 1;
  int64 question_id = 2;
  int32 question_report_reason = 3;
  string question_report_content = 4;
  int64 question_report_writer_id = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message QuestionListResponse {
  repeated QuestionListItem questions = 1;
  bool has_next = 2;
  int32 current_page = 3;
  int32 total_page_num = 4;
}

message QuestionListItem {
  int64 question_id = 1;
  int64 question_category = 2;
  string question_writer_name = 3;
  string question_writer_profile = 4;
  string question_title = 5;
  string question_content = 6;
  bool question_urgency = 7;
  string question_answer_type = 8;
  bool is_answered = 9;
  int32 answer_count = 10;
  google.protobuf.Timestamp created_at = 11;
}

message CategoryRecommendationResponse {
  int64 category_id = 1;
  string category_name = 2;
}

message SimilarQuestionItem {
  int64 question_id = 1;
  string question_title = 2;
  string question_content = 3;
  int64 question_category = 4;
  bool question_urgency = 5;
  string question_answer_type = 6;
  bool is_answered = 7;
  google.protobuf.Timestamp created_at = 8;
}

message SimilarQuestionResponse {
  repeated SimilarQuestionItem similarQuestions = 1;
}

message QuestionDetailResponse {
  QuestionCreateResponse question = 1;
  Authority authority = 2;
}

message PopularPostItem {
  int64 question_id = 1;
  int64 category_id = 2;
  string profile_url = 3;
  string nickname= 4;
  string title = 5;
  string content = 6;
  bool is_answered = 7;
  int32 answer_count = 8;
  google.protobuf.Timestamp created_at = 9;
}

message GetPopularPostResponse {
  repeated PopularPostItem post = 1;
}

message GetMyQuestionResponse {
  repeated PopularPostItem post = 1;
  bool has_next = 2;
  int32 current_page = 3;
  int32 total_page_num = 4;
}