syntax = "proto3";

package com.exit.common;

option java_multiple_files = true;
option java_package = "com.exit.common.grpc";
option java_outer_classname = "ResponseServiceProto";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "question/question.proto";

service ResponseService {
  rpc AnswerAdopt(AnswerAdoptRequest) returns (AnswerAdoptResponse);
  rpc AnswerReport(AnswerReportRequest) returns (AnswerReportResponse);
  rpc GetDetailResponse(GetDetailResponseRequest) returns (GetDetailResponseResponse);
  rpc AnswerCreate(AnswerCreateRequest) returns (AnswerCreateResponse);
  rpc AnswerRecommend(AnswerRecommendRequest) returns (AnswerRecommendResponse);
  rpc UpdateResponse(UpdateResponseRequest) returns (UpdateResponseResponse);
  rpc DeleteResponse(DeleteResponseRequest) returns (google.protobuf.Empty);
}

// Request messages
message AnswerAdoptRequest {
  int64 response_id = 1;
}

message AnswerReportRequest {
  int64 response_id = 1;
  int64 response_report_writer_id = 2;
  string response_report_title = 3;
  string response_report_content = 4;
}

message GetDetailResponseRequest {
  int64 question_id = 1;
  int64 user_id = 2;
  int32 page_num = 3;
  int32 size = 4;
}

message AnswerCreateRequest {
  int64 question_id = 1;
  string response_content = 2;
  int64 response_writer_id = 3;
  bool response_is_anonymous = 4;
  repeated UploadBytesRequest images = 5;
}

message AnswerRecommendRequest {
  int64 response_id = 1;
  int64 user_id = 2;
}

message UpdateResponseRequest {
  int64 response_id = 1;
  string content = 2;
}

message DeleteResponseRequest {
  int64 response_id = 1;
}

// Response messages
message ResponseDetail {
  int64 response_id = 1;
  int64 response_writer_id = 2;
  string response_writer_name = 3;
  string response_content = 4;
  bool response_adopt = 5;
  repeated string urls = 6;
  int32 like_count = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  string profile = 10;
  bool is_ai = 11;
}

message AnswerAdoptResponse {
  int64 response_id = 1;
  bool response_adopt = 2;
  google.protobuf.Timestamp updated_at = 3;
}

message AnswerReportResponse {
  int64 response_report_id = 1;
  int64 response_id = 2;
  string response_report_title = 3;
  string response_report_content = 4;
  int64 response_report_writer_id = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message GetDetailResponseResponse {
  repeated ResponseDetail responses = 2;
  bool has_next = 3;
  int32 current_page = 4;
  int32 total_page_num = 5;
  Authority authority = 6;
}

message AnswerCreateResponse {
  int64 response_id = 1;
  int64 question_id = 2;
  string response_content = 3;
  int64 response_writer_id = 4;
  repeated string image_urls = 5;
  google.protobuf.Timestamp created_at = 6;
}

message AnswerRecommendResponse {
  int64 response_id = 1;
  int32 count = 2;
  bool is_recommended = 3;
}

message UpdateResponseResponse {
  int64 response_id = 1;
  string content = 2;
}