syntax = "proto3";

package com.exit.common;

option java_multiple_files = true;
option java_package = "com.exit.common.grpc";
option java_outer_classname = "UserServiceProto";
import "google/protobuf/empty.proto";
import "question/question.proto";

service UserService {
  rpc GetUserName(GetUserNameRequest) returns (GetUserNameResponse);
  rpc GetUserNames(GetUserNamesRequest) returns (GetUserNamesResponse);
  rpc IncreaseReportCount(IncreaseReportCountRequest) returns (google.protobuf.Empty);
  rpc UpdateAdditionalUserInfo(UpdateAdditionalUserInfoRequest) returns (UpdateAdditionalUserInfoResponse);
  rpc GetUserNameAndProfile(GetUserNameRequest) returns (UpdateAdditionalUserInfoResponse);
  rpc GetUsersNameAndProfile(GetUsersNameAndProfileRequest) returns (GetUsersNameAndProfileResponse);
  rpc GetFcmToken(GetFcmTokenRequest) returns (GetFcmTokenResponse);
  rpc UpdateDevice(UpdateDeviceRequest) returns (google.protobuf.Empty);
}

// request
message GetUserNameRequest {
  int64 user_id = 1;
}

message GetUserNamesRequest {
  repeated int64 user_id = 1;
}

message IncreaseReportCountRequest {
  int64 user_id = 1;
}

message UpdateAdditionalUserInfoRequest {
  int64 user_id = 1;
  string user_name = 2;
  UploadBytesRequest image_file = 3;
}

message GetFcmTokenRequest {
  int64 user_id = 1;
}

message UpdateDeviceRequest {
  int64 user_id = 1;
  string device_id = 2;
  string fcm_token = 3;
}

message GetUsersNameAndProfileRequest {
  repeated int64 user_id = 1;
}

// response
message GetUserNameResponse {
  string user_name = 1;
  bool success = 2;
  string message = 3;
}

message UserIdAndNameInfo {
  int64 user_id = 1;
  string user_name = 2;
}

message GetUserNamesResponse {
  repeated UserIdAndNameInfo userInfo = 1;
}

message UpdateAdditionalUserInfoResponse {
  int64 user_id = 1;
  string user_name = 2;
  string user_profile = 3;
}

message GetFcmTokenResponse {
  repeated string fcm_token = 1;
}

message GetUsersNameAndProfileResponse {
  repeated UpdateAdditionalUserInfoResponse user_info = 1;
}