server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=3

# gRPC Client 설정 (Eureka 기반 로드밸런싱)
grpc:
  client:
    user-service:
      address: discovery:///user-service  # Eureka에서 서비스 발견
      negotiation-type: plaintext

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true