syntax = "proto3";

package com.exit.common;

option java_multiple_files = true;
option java_package = "com.exit.common.grpc";
option java_outer_classname = "QuizServiceProto";

import "google/protobuf/empty.proto";

service QuizService {
  rpc GetCategoryStatistics(GetCategoryStatisticsRequest) returns (GetCategoryStatisticsResponse);
  rpc GetQuizByCategory(GetQuizByCategoryRequest) returns (GetQuizResponse);
  rpc GetQuizById(GetQuizByIdRequest) returns (GetQuizResponse);
  rpc SubmitAnswer(SubmitAnswerRequest) returns (SubmitAnswerResponse);
  rpc GetSolvedQuiz(GetSolvedQuizRequest) returns (GetSolvedQuizResponse);
  rpc GetTodayQuiz(google.protobuf.Empty) returns (GetTodayQuizResponse);
}

// request
message GetCategoryStatisticsRequest {
  int64 user_id = 1;
}

message GetQuizByCategoryRequest {
  int64 user_id = 1;
  int64 category_id = 2;
}

message GetQuizByIdRequest {
  int64 user_id = 1;
  int64 quiz_id = 2;
}

message SubmitAnswerRequest {
  int64 user_id = 1;
  int64 quiz_id = 2;
  string answer = 3;
}

message GetSolvedQuizRequest {
  int64 user_id = 1;
  repeated int64 category_id = 2;
  int32 page_num = 3;
  int32 size = 4;
}

// response
message CategoryStat {
  int64 category_id = 1;
  int32 category_quiz_num = 2;
  int32 category_solved_num = 3;
  bool can_solve_quiz = 4;
}

message GetCategoryStatisticsResponse {
  repeated CategoryStat category_stat = 1;
}

message GetQuizResponse {
  int64 quiz_id = 1;
  int64 quiz_category_id = 2;
  string quiz_title = 3;
  repeated string quiz_content = 4;
  string quiz_type = 5;
  string quiz_correct_answer = 6;
  string quiz_additional_information = 7;
}

message SubmitAnswerResponse {
  bool has_next = 1;
}

message AttemptQuiz {
  int64 quiz_id = 2;
  string quiz_title = 3;
}

message GetSolvedQuizResponse {
  repeated AttemptQuiz attempt_quiz = 1;
  bool has_next = 2;
  int32 current_page = 3;
  int32 total_page_num = 4;
}

message GetTodayQuizResponse {
  int64 quiz_id = 1;
}
