server:
  port: 0  # 랜덤 포트 (여러 인스턴스 실행 가능)

spring:
  application:
    name: user-service
  profiles:
    active: dev

# gRPC 서버 설정
grpc:
  server:
    port: 0  # 랜덤 gRPC 포트

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # gRPC 포트를 메타데이터에 추가
    metadata-map:
      grpc-port: ${grpc.server.port}
      grpc-service: user-service