# OAuth2 Configuration
KAKAO_CLIENT_ID: 6d70a269c951d3eb86f2161e93c6771b
KAKAO_CLIENT_SECRET: eorh3vwcaLjOJtrsFwCYbCJ2tkrvkg2f
NAVER_CLIENT_ID: vtryCh7rmNpdbUvKpaeu
NAVER_CLIENT_SECRET: aVfPT9bGC_
DB_USERNAME: exit_user
DB_PASSWORD: exit_password
  
spring:
  servlet:
    multipart:
      max-file-size=10MB
      max-request-size=10MB