# OAuth2 Configuration
KAKAO_CLIENT_ID: ffd989f1cbeed34cd2354779ace61298
KAKAO_CLIENT_SECRET: x9aD1dIaN3T6NAGY5YXuBhgA9w7lch4O
NAVER_CLIENT_ID: Tkj3eiWOGrKPLUHocjIu
NAVER_CLIENT_SECRET: t7K2ed3CvS
DB_USERNAME: exit_user
DB_PASSWORD: exit_password